### ISSUE TITLE
Group color formatting does not end in /who

### ISSUE THREAD

**Issue by Crashdoom** [AvilanceLtd/StarryboundServer#23]
Color does not seem to end after a username in /who

![screenshot 2013-12-29 06 04 46](https://f.cloud.github.com/assets/575410/1819006/74be0686-704f-11e3-98dc-f0769fbf82e6.png)

**Comment by TheOpalium** [comment]
Fixed (see 3a5fdb1893d6f4dd7280d576a5c4e6d5649fb051)
