### ISSUE TITLE
Can't Connect To Server

### ISSUE THREAD

**Issue by 100chilly** [AvilanceLtd/StarryboundServer#24]
[EXCEPTION] ClientThread Exception: System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at com.avilance.Starrybound.Client.run()

I'm guessing its because i'm not on another computer while trying to run the server and the game?

**Comment by Crashdoom** [comment]
Can you give me some more information on the issue? How are you connecting to the server, where is your client located? Does this occur for any other users?
