### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by Crashdoom** [AvilanceLtd/StarryboundServer#27]
An addon system to allow modders to create custom implementations of the system without the need to edit the core binary. Maintains security and would allow better debugging of issues relating to addon code.

**Comment by Mr00Anderson** [comment]
So like minecrafts bukkit, with plug-ins?

**Comment by Crashdoom** [comment]
@Underbalanced That would essentially be the goal, it saves people having to use custom binaries in order to add functionality. It'll also make it easier for us to help debug issues with the plugins :P

**Comment by Mr00Anderson** [comment]
Guess i better learn C#. I know all about networking and a little java, and python.  So much I want to learn, but work is networking all day so its hard to memorize new things. ha

**Comment by Crashdoom** [comment]
@Underbalanced We'll try and give as much help as possible by preparing documentation and such prior to releasing the feature. :)
