### ISSUE TITLE
RCON (Remote Console) System

### ISSUE THREAD

**Issue by Crashdoom** [AvilanceLtd/StarryboundServer#29]
Remote Console system that can be used to manage the server either from a desktop application or command line prompt via a set password in the config.json file.

RCON port should be assigned either +/- 1-3 ports from the proxy port by default but can be customized accordingly. Use of ports < 1024 should be disallowed or restricted (root only on Linux systems).

The RCON user should be able to do basic functionality as if they were a superadmin client, e.g. kick, ban, broadcast, group assignments and change system variables. However, they could be unaffected by targeting commands and not marked as an active player on the server. RCON command usage & access attempts should be logged to a separate rcon.log file.

**Comment by Crashdoom** [comment]
Feature in progress.

**Comment by mauzao9** [comment]
@Crashdoom is the RCON system ready on this 1.3 release?

**Comment by Crashdoom** [comment]
Actually, I'm still working on it :P Thanks for the update I forgot about re-opening this issue!
