### ISSUE TITLE
Can't Connect to Server

### ISSUE THREAD

**Issue by 100chilly** [AvilanceLtd/StarryboundServer#30]
[INFO] [10.0.0.6] Accepting new connection.
[INFO] [10.0.0.6] Dropped by parent Server for End of stream

I've forwarded the ports. Built the binary from the Dev branch. Also I mentioned this in my other ticket, I'm running the proxy server and the client off the same computer. I'm connecting though my computer's ip. I can't confirm if this will happen to my other users as none have tired connecting yet. I'm willing to let @Crashdoom @Zidonuke connect if they so wish to help confirm if it will bounce other people.

**Comment by ghost** [comment]
LAN IPs work, I cannot reproduce this issue.

**Comment by 100chilly** [comment]
@Zidonuke Quick question: How exactly do you run yours? I've just been running everything as default but it still wont let me connect.
