### ISSUE TITLE
Protect Spawn World Further

### ISSUE THREAD

**Issue by Mr00Anderson** [AvilanceLtd/StarryboundServer#31]
Players can still place items like turrets, torches.

Remove splash damage, so they cannot use bombs or spawn meteor showers that rape the spawn planet.

Also unable to place environmental items like lava?

**Comment by ghost** [comment]
Object protections added. You can protect the spawn already with the projectileBlacklistSpawn, I am unsure what projectiles cause damage at this time, please come up with a list and we can add it as default.

**Comment by Mr00Anderson** [comment]
How are they suppose to be written in the config so i know what to look for when going through the mods and assets trying to find the projectiles

**Comment by ghost** [comment]
The parent server will never understand modded projectiles if they are a completely new projectile type.
For existing projectiles you can block those. in assets/projectiles/ in any .projectile file, look for "projectileName" : "testswoosh3", That is the key you add to 

"projectileBlacklist": [
    "testswoosh3",
    "friendlybubble"
  ],
