### ISSUE TITLE
fatal error logged

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#32]
hey guys, I notice this one seems to happen often and causes an auto restart.  starbound_server.exe throws a corresponding error event into the windows event log but I don't think it would help you (not a strack trace).   IP's and UUID's redacted with "***"

```
[INFO] [Numbers21][196] joined with UUID ***
[INFO] [MustacheManCRK] Dropped by parent Client for An existing connection was forcibly closed by the remote host
[INFO] [Numbers21] Dropped by parent Server for An existing connection was forcibly closed by the remote host
[INFO] [Universe] [Triela]: you in X?
[INFO] [***] Accepting new connection.
[INFO] Loaded persistant user storage for MustacheManCRK
[INFO] [MustacheManCRK][197] joined with UUID ***
[INFO] [7****] Accepting new connection.
[INFO] [Universe] [raymon]: mhmmm
[INFO] Loaded persistant user storage for Numbers21
[INFO] [Numbers21][198] joined with UUID ***
[INFO] [37***] Accepting new connection.
[INFO] [37***] Dropped by parent Server for End of stream
[FATAL ERROR] Starbound TcpServer has closed, no new clients will be accepted - Forcing a restart in 30 seconds.
[INFO] [Numbers21] Dropped by parent Client for An existing connection was forcibly closed by the remote host
[FATAL ERROR] The server has encountered a fatal error and cannot continue. Restarting in 10 seconds.
```

**Comment by Crashdoom** [comment]
This is an issue with the starbound_server.exe and cannot be fixed by us, we force a restart when the server encounters this error.

"Starbound TcpServer has closed, no new clients will be accepted - Forcing a restart in 30 seconds." This means the Starbound parent server's connection listener has closed due to an exception and is irrecoverable by us or the server, the only fix is a restart.

**Comment by saybrook** [comment]
Yes I know. I thought you guys wanted all errors documented even if they are from starbound proper.

**Comment by Crashdoom** [comment]
Yeah, we're passing as much on as we can to the developers when we get issues we can't fix, but we're still marking them as closed once we have.

**Comment by saybrook** [comment]
Ok cool
