### ISSUE TITLE
dev branch - game port forced to 21025 causes fatal error, cant start server.

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#33]
For some reason the current dev build forces starboud.config  gameport to 21025.

Even when I delete the file allowing starrybound to create  new one it assigns it to 21025 which of course bombs the server out because it cant bind to that port.

**Comment by Crashdoom** [comment]
Fixed in 9ea86639e5d6e288887dac26c67ce927df1cd533
