### ISSUE TITLE
WarpCommand player location

### ISSUE THREAD

**Issue by Crashdoom** [AvilanceLtd/StarryboundServer#4]
Player location is not updated with the WarpCommand and remains :0:0:0:0:0 until you warp to another/to the same planet.

**Comment by Crashdoom** [comment]
Requiring input from @Zidonuke with R&D on the issue. Currently blocking editing while co-ordinates are :0:0:0:0:0, re-warping to a planet fixes the co-ordinate issue.

**Comment by Crashdoom** [comment]
Commit 194f38e58c75ce98ff8af232b3819bbbed5d1a98 appears to have stopped the issue with players being unable to edit on other planets as a work around.

**Comment by ghost** [comment]
EnvironmentUpdate will always have latest location data from the perspective of the server and is secure.
