### ISSUE TITLE
Backup System

### ISSUE THREAD

**Issue by Crashdoom** [AvilanceLtd/StarryboundServer#40]
A system to backup the universe to a save directory and optionally zip them to reduce disk usage. Backup of the starrybound configuration files should also be added to a separate backup file for optional restoration as required.

The server admin should be able to trigger a backup or make it scheduled based on a predetermined time of day or interval.

**Comment by majorcyto** [comment]
Might want to update..

"reduce dick usage"

to Disk usage lol.

**Comment by Crashdoom** [comment]
@majorcyto I hadn't even noticed that XD
