### ISSUE TITLE
UUID auth does not appear to be working

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#42]
I have deleted/recreated my  'darkos.json' in the players folder and set the group to superadmin and it does not recognize me as superadmin.

I let starrybound recreate the file while offline, then login, then log off, then change the group and login.. still doesn't work.

**Comment by saybrook** [comment]
sorry this is with latest dev 1.2.1.19937

**Comment by Crashdoom** [comment]
Duplicate of issue #41
