### ISSUE TITLE
#41 was fixed in 27979 but now the config gameport gets hard reset to 21025 again

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#43]

**Comment by Crashdoom** [comment]
The development branch is currently broken, please use the official 1.2.1.1 release for the moment.

**Comment by saybrook** [comment]
Understood.  That's what us testers are for!

**Comment by Crashdoom** [comment]
I'm unable to reproduce this error on the latest development version 51a5f23ec41698038019a6561c89faa4af66ad63. It will reset it to 21025 once it's started up but each launch will use the server port specified in your config.json as the Starbound server port.
