### ISSUE TITLE
Auto-Restart doesn't support mono..?

### ISSUE THREAD

**Issue by majorcyto** [AvilanceLtd/StarryboundServer#45]
In the previous version of starrybound it auto-restarted just fine by opening a new terminal. This time when i checked on it, it said "The auto-restarter does not support mono" wut..

**Comment by Crashdoom** [comment]
Feature re-added in 00f001559f83c511635f27bdbf71c8bbcd7d7254. Please update us if you encounter any errors, there is a toggle to disable this feature in the config.json file.
