### ISSUE TITLE
IRC Bridge support

### ISSUE THREAD

**Issue by wmgregory** [AvilanceLtd/StarryboundServer#49]
I'd like to suggest simple IRC bridge support, would be very helpful just to see what is happening from IRC.

**Comment by Crashdoom** [comment]
What messages would you like to see from the IRC bridge? Join/leave, chat, command actions? We can add a lot of these as toggle options :)

**Comment by mauzao9** [comment]
It's already possible to make such, but with RCON would be nice to be able to make commands into the server, even be able to whisper users, etc.. That via IRC makes stuff easier :)

**Comment by wmgregory** [comment]
I could list so many things that would be useful... I even edited someone's perl scripts to cater: http://pastebin.com/6zsJEXTa
- Join (toggle ip)
- leave
- chat (group)
- total users
- worlds accessed (toggle) -  (cood/difficulty/etc)
- Commands by players (toggle)

**Comment by wmgregory** [comment]
Oh, are you able to add talking to to the server and executing commands in the irc bridge to kick/ban etc from IRC? Not sure how you can do that without having direct access to the server console.

**Comment by Crashdoom** [comment]
Sure, we could handle that via the RCON system :)
