### ISSUE TITLE
Fatal Error encountered upon loading.

### ISSUE THREAD

**Issue by Sno-sno** [AvilanceLtd/StarryboundServer#50]
[STAR] Info: Server version 'Beta v. Angry Koala' '628' '428'
[STAR] Info: Scanning for router for portforwarding
[STAR] Info: Done scanning for router for portforwarding
[STAR] Info: Creating world alpha:-14957502:-41347276:-1869027:4:10
[STAR] Info: Generating 1 dungeons
[STAR] Info: Placing dungeon at (1360, 419)
[WARN] Parent Server [UniverseServer::createWorld] lagged for 5.644 seconds
[STAR] Info: Shutting down Star::Root
[STAR]
[FATAL ERROR] The server has encountered a fatal error and cannot continue. Restarting in 5 seconds.
[INFO] Starting graceful shutdown...
[INFO] Waiting 10 seconds for all clients to leave.
[INFO] Graceful shutdown complete.
[WARN] Auto Restarter doesn't support Mono. Exiting.

**Comment by Crashdoom** [comment]
An error should have been posted in a server error file in the starrybound directory, could you grab the last message from that file for me?

**Comment by Sno-sno** [comment]
Warn: Failed to place dungeon object: huntingtrophy1 direction: 0 position: (6014, 1263)
Warn: Failed to place dungeon object: huntingtrophy3 direction: 0 position: (4, 1263)
Warn: Object statuspod does not have a price set
Warn: Slow asset 0.06 : /plants/trees/forest/stem/something/branch1.png
Warn: Slow asset 0.06 : /plants/trees/forest/stem/something/branch1.png
Warn: Object floweryellow does not have a price set
Warn: Perf: UniverseServer::createWorld millis: 5190
Info: Shutting down Star::Root
Error: Fatal Exception Caught: ConfigurationException: Could not convert config entry 'bind' to string
/opt/gameservers/starbound/linux64/starbound_server(_ZN4Star13StarExceptionC2ERKSs+0xfe) [0xaad97e]
/opt/gameservers/starbound/linux64/starbound_server() [0x5346d1]
/opt/gameservers/starbound/linux64/starbound_server(_ZNK4Star13Configuration9getStringERKNS_6StringE+0xaf) [0x533aaf]
/opt/gameservers/starbound/linux64/starbound_server(_ZN4Star14UniverseServer3runEv+0xbc) [0x577d3c]
/opt/gameservers/starbound/linux64/starbound_server() [0x50eb72]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f065932076d]
/opt/gameservers/starbound/linux64/starbound_server() [0x512bdd]

**Comment by Sno-sno** [comment]
Odd, i deleted the config file, and it's now working, Didn't even modify the config first time :/
