### ISSUE TITLE
Issues closed?

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#52]
Because they were resolved or is the project being abandoned?

**Comment by traxo-xx** [comment]
It's dead: https://github.com/AvilanceLtd/StarryboundServer/blob/master/README.md

But cyberkitsune is working on a fork: https://github.com/cyberkitsune/StarshipServer

**Comment by Crashdoom** [comment]
I'm going to leave this issue open, I'm glad that someone is making good use of the project that had no malice behind it at all. @cyberkitsune Thank you and good luck :)

**Comment by Crashdoom** [comment]
Issue closed - Project is being actively maintained by @AvilanceLtd team, please direct any PR inquiries to crashdoom[at]avilance.com. Builds of the project will be maintained by Atlassian On-Demand (https://www.atlassian.com/), subject to approval for the safety and security of all users.

**Comment by saybrook** [comment]
so..you guys are back?  shall I continue bug squashing then? :)

**Comment by mauzao9** [comment]
I got confused about the update message. D:
@Crashdoom you are part of @AvilanceLtd but on the page it says that you will take no part of it.

**Comment by Crashdoom** [comment]
@saybrook Yeah, I'm quelling any issues about security by setting up a Bamboo with Atlassian On-Demand and Amazon EC2 at my own expense :)

@mauzao9 Which page is that? I did put on the readme that we weren't handling it, but we have redacted that and will be continuing with the project. :+1:
