### ISSUE TITLE
Active project?

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#53]
Just wondering if you guys are updating since the patch.

thanks!

**Comment by traxo-xx** [comment]
I think this answers your question:
https://github.com/AvilanceLtd/StarryboundServer/pull/54

**Comment by saybrook** [comment]
indeed. and good to see!

**Comment by Crashdoom** [comment]
All of our pre-compiled builds are available at https://avilance.atlassian.net/builds - They are built securely by the third-party provider Atlassian. However you are welcome and encouraged to build from source where possible :+1:
