### ISSUE TITLE
Group processing exception

### ISSUE THREAD

**Issue by bigloof** [AvilanceLtd/StarryboundServer#57]
[DEBUG] [StarryboundServer::changeState]:StateChange requested by StarryboundServer::Main to Starting: Not Specified
-- Log Start: 1/28/2014 2:31:12 PM --
[INFO] ####   Avilance Ltd. Starrybound Server   ####
[INFO] ####       Licensed under the GPLv3       ####
[INFO] Version: 1.3.0.22985 (635)
[INFO] Starrybound config loaded successfully.
[INFO] Starbound server config loaded successfully.
[FATAL ERROR] A fatal exception occurred while processing the groups (Groups::ProcessGroups): System.RankException: Parent (moderator) for group admin does not exist!
   at com.avilance.Starrybound.Permissions.GroupFile.ProcessGroups(List`1 groupList)

[INFO] ####   Copyright (c) Avilance Ltd. 2013   ####
[INFO] Loading Starrybound Server...
[INFO] Starrybound groups loaded successfully.
[INFO] ##############################################
[DEBUG] [SetupConfig]:This was compiled in DEBUG, forcing debug logging!
[INFO] Starting graceful shutdown...
[DEBUG] [Shutdown]:Requesting starbound_server close.

**Comment by Crashdoom** [comment]
Please try using the latest version: https://avilance.atlassian.net/builds/browse/STAR-MAS-8 - This was a bug that should be fixed in STAR-MAS-5.
