### ISSUE TITLE
Config.json resets on server start - Linux/Mono

### ISSUE THREAD

**Issue by majorcyto** [AvilanceLtd/StarryboundServer#58]
Config.json and groups.json, each load to default on server startup. Ill change all the settings in it, then as soon as the server starts.. it changes to default config file settings it will not save anything i put in, just reverts instead.

Motd.txt and rules.txt is fine, i guess because it isnt dynamically loading it like a .json?

The player .json files DO hold data correctly, i manually changed my rank to [SA] group and it worked fine i logged in and i was in that group correctly.

I'm using Linux, and Mono...
Using Build # 8 from Atlassian Bamboo

**Comment by Crashdoom** [comment]
Is this using the Master or Development branch?

**Comment by Crashdoom** [comment]
Also, is there any message in the console about this error? If it's resetting to default there should be some form of reason listed before/after it does it.

I'm not able to replicate the issue using STAR-MAS-8 (https://avilance.atlassian.net/builds/browse/STAR-MAS-8) on my own server running Debian 7 (Linux64) and Mono

**Comment by majorcyto** [comment]
Im using Master branch.

This is really strange though, i decided to try to change some settings and use /reload config and /reload groups in game. Well, it didn't work (it said it did) but i changed the player count.. reloaded did /who and it was still set at old value. No error in log either though..?

So then i did a /restart in-game, the server restarted and it came up.. of course it said "this file has been changed, reload?" so i did.. and my values stayed!?!? And it loaded them correctly in-game.. so this is a weird work around but i dunno..

---

Also is this still the format for this..?

```
 "defaultSpawnCoordinates": "alpha:93182359:13375211:-17617137:3:8",
```

---

**Comment by Crashdoom** [comment]
I'll take a look into this, also I don't think spawn protection is working yet in regards to projectiles, block breaking/building prevention works fine, due to a change in the protocol. The format there is correct - Sector:X:Y:Z:Planet:Satellite

**Comment by majorcyto** [comment]
Im pretty sure setting default spawn planet is not working..

I set starbound server config to true..
Set default spawn coordinates tot hat above...
Spawn world protection true..

Reload config, restart server - > make new char -> char is above nothing in space and cant beam down..

**Comment by Crashdoom** [comment]
Make sure you're not using any old spawn coordinates as the world generation has changed so old coordinates are no longer valid. That may explain why you're unable to beam down.

**Comment by noxturno** [comment]
I have this same issue, my config file resets to default  :(  linux debian 7

**Comment by majorcyto** [comment]
I'm not, im beaming down to the planet and pulling it straight out of console log.

**Comment by Crashdoom** [comment]
The latest build: STAR-DEV-15 (Development build 15; https://avilance.atlassian.net/builds/browse/STAR-DEV-15) should fix the issues with the protection system.

@majorcyto Can you confirm if the issue occurs in the latest version?

**Comment by Crashdoom** [comment]
Comment taken from Issue #69:
"Is this using a pre-compiled version or a compilation from source? I haven't tested compiling on Linux but can confirm it works on Windows (using VS2013)."

**Comment by hbrewitt** [comment]
Pre-compiled as per Atlassian. I'll update to Dev build 15 and report back now.

Updated and the same persists.

**Comment by hbrewitt** [comment]
Found a fix for this: 

I did a fresh install of the server and the missing .dll files- I think the error was with trying to start the server previous to having the .dll files in the directory. Thus, ruining some of the .json magic. 
To fix the following steps were taken; 

Deleted Starrybound Folder
Deleted the 3 .dll files from within /linux64
Deleted Starrybound_server.exe

Downloaded Master Build #9 from Atlassian. 
Downloaded a previous .zip file of Starrybound to use the .dll files from- I used this: https://www.dropbox.com/s/2izldhs1z9gbtcm/starrybound-server-1.2.1.1.zip
(Remember not to upload the Starrybound_server.exe from this zip!!)
Upload the 4 .dll files within the zip- (Not entirely sure whether System.Numerics.dll is required- I uploaded it anyway). 
Upload Starrybound_server.exe to your /linux64 directory. 

Run the server. 
Hey presto- everything worked. 
Hope this is of some help :)

**Comment by noxturno** [comment]
yay some hope !!, I will try this !!!

Edit I did that and it all works great !!!!!!, only issue now is the spawn planet, I set it up but no one can go down to the planet also noone can leave their ships they try to shit on the control panel of the ship but the windown closes.

**Comment by Crashdoom** [comment]
That's an issue with the Starbound server not sending an update to the client, get them to try /planet or the warp down button. Also ensure the coordinates are valid, the world generation changed in the update so old coordinates aren't valid in Furious Koala.

**Comment by noxturno** [comment]
what would be the steps I need to follow so I can get a spawn world to work ? also would people with mods crash the server ?

**Comment by noxturno** [comment]
btw this issue of the config resetting still not fixed on the latest build.
