### ISSUE TITLE
Can the dev branch be updated and tested before committing to master?

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#60]
just curious, i am getting confused on which branch is getting the latest commits. 
I am running build 8 right now and it is doing well.

**Comment by majorcyto** [comment]
Just use master for now, its the one building the latest on atlassian at the moment. I also used dev branch at first lol.

**Comment by Crashdoom** [comment]
Sorry, once I'd got it working on my test server I pushed to the master branch, I'm going to go back to development for new feature additions/bugfixes but the master is currently the most up to date as of this post.

**Comment by saybrook** [comment]
ok great thanks for letting us know
