### ISSUE TITLE
Windows error dialogue prevents auto-restart

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#61]
Not sure there is anything we can do about this.  If starbound_server crashes and generates the typical windows error dialogue this prevents starrybound from restarting the server until a user click's OK on the dialogue to close it.

**Comment by Crashdoom** [comment]
I can see if there's a workaround but this may just be Windows way of prompting the user about it and may not have a fix. I'll try and see what I can find.

**Comment by saybrook** [comment]
yea.. the only reason i bring it up is 9 times out of 10 when star bound crashes and prompts a restart this dialogue box is fired off and prevents the auto-restart.

**Comment by igromanru** [comment]
This is not a neat solution, but you could use WinApi for [looking](http://msdn.microsoft.com/en-us/library/windows/desktop/ms633499%28v=vs.85%29.aspx) for the dialog and send a ["message"](http://msdn.microsoft.com/en-us/library/windows/desktop/ms644950%28v=vs.85%29.aspx) to close it or press "OK".
