### ISSUE TITLE
[Feature Request] /spawn command

### ISSUE THREAD

**Issue by majorcyto** [AvilanceLtd/StarryboundServer#63]
I know we have warp ship, etc.. and i know we can set planet as default but, can we get a dedicated /spawn command?

It'll basically work like warp ship i guess, but always go to the default coords in the config file. :+1:

**Comment by Crashdoom** [comment]
This has already been implemented! :P If you use /spawn while on your ship it will take you to the spawn planet set in the starbound.config file.

**Comment by majorcyto** [comment]
Oh, im sorry man.. i just saw the permission node for it. Fail.
