### ISSUE TITLE
Auth system

### ISSUE THREAD

**Issue by mauzao9** [AvilanceLtd/StarryboundServer#64]
Heya.

We have been trying to get our server more locked to our community sites, to have more control and also site activity and not randomly players popping at the server and leaving, still i see no good on passwords but yes on the Auth System.

So my suggestion is do what the Russian servers did with their wrapper, make the wrapper itself auth against a database and not use the vanilla files that require a restart.

If wrapper is able to at least to check the auth data against a database then we can make this work! :)

**Comment by Crashdoom** [comment]
It shouldn't be a problem for us to get this working, we may try to get a plugin system done first and make that as a plugin instead of a core feature.

**Comment by majorcyto** [comment]
I agree, plugin system would be more beneficial then add it as a core plugin that way its default, and plugins could just hook through it to one database (and just insert tables instead)

**Comment by mauzao9** [comment]
The idea may be, players can join normally without account, but they are in some "guest" group where they can't, maybe move from spawn (like tshock do) if possible, or just limited permissions till they register one account. :)

**Comment by DankBud** [comment]
^Guest group's just like in tshock. Good suggestion, It's getting annoying having to delete a players account, just because they re-installed starbound.
