### ISSUE TITLE
[Request] AutoRestart with config

### ISSUE THREAD

**Issue by igromanru** [AvilanceLtd/StarryboundServer#66]
Can you please implement a feature that allow to set AutoRestart in the config file and restart the Starbound server automatic?

Starbound server got sometimes memory problems/leaks. It is very helpful to restart the server each few hours.

**Comment by majorcyto** [comment]
This is already a pre enabled feature

**Comment by saybrook** [comment]
yes this does work, although the windows error dialogue can prevent it from working until you close the dialogue box.

**Comment by Crashdoom** [comment]
@igromanru As in a timed restart? So restarting every X hours or so?

**Comment by igromanru** [comment]
@Crashdoom Yes, I mean a timed restart in a loop, that can me configurate in the config.json.
