### ISSUE TITLE
Config files reset after each server restart.

### ISSUE THREAD

**Issue by hbrewitt** [AvilanceLtd/StarryboundServer#69]
Hi, after each server crash all the config files are corrupted (according to the server startup) 
[EXCEPTION] Starrybound config is unreadable - Re-creating config with default values

Essentially everything within the Starrybound folder is apparently corrupted. 
If you need any more information that could be of use I'm happy to get it for you,
Thanks

**Comment by Crashdoom** [comment]
Is this using a pre-compiled version or a compilation from source? I haven't tested compiling on Linux but can confirm it works on Windows (using VS2013).

**Comment by Crashdoom** [comment]
Closed - Merged with issue #58
