### ISSUE TITLE
CPU usage through the roof

### ISSUE THREAD

**Issue by Zallist** [AvilanceLtd/StarryboundServer#7]
The CPU usage right now is through the roof (a whole CPU core).
This is caused by the crashMonitor thread.

Starrybound.cs -> crashMonitor()

Add 
System.Threading.Thread.Sleep(2000); 
or make this event-based to stop it from destroying servers.

**Comment by Crashdoom** [comment]
Fixed in commit a1ba1857e4b719a91d552a22bc3d141685a02770
