### ISSUE TITLE
[Question] about some commands .

### ISSUE THREAD

**Issue by noxturno** [AvilanceLtd/StarryboundServer#71]
I would like to know if there is a way to remove the ability for anyone to do /find , some people dont wanna be found and just wanna travel alone I was going thru the group perms and I couldnt find it, also the spawn protection is not working atm :(

thanks in advance.

**Comment by mauzao9** [comment]
It's one permission:
client.find: Allows the use of /find to find your or another player's coords.
;)

I believe it's working.

**Comment by noxturno** [comment]
yeah I found it they had client.\* got it :)
