### ISSUE TITLE
Can't kick/ban players even as superadmin. 

### ISSUE THREAD

**Issue by hbrewitt** [AvilanceLtd/StarryboundServer#72]
I constantly get "You don't have permission to target this user" 

Not sure whether players are getting a bypass within the client.\* permission? 
I can't even find the permissions wiki page anymore :(

**Comment by Crashdoom** [comment]
If you check the groups.json there's a new targetpower option, the higher the power the more authority. I didn't get a chance to set a default value for existing groups, sorry about that!

**Comment by hbrewitt** [comment]
I uploaded my previous version of a groups file- so I don't have a copy with the targetpower option. Do you have a specific permission node? Or is there a certain way I need to set it up? 
Thanks
