### ISSUE TITLE
huge problem

### ISSUE THREAD

**Issue by noxturno** [AvilanceLtd/StarryboundServer#75]
people can wait for an admin to logout then create a new character with the same name and login and get admin powers....

**Comment by HyperSilence** [comment]
I actually tried this to test it out, and you get this error. 
Which is what happens when you try to join the server with the same name as someone else.
Even if they are not online at the time. 
![nope](https://f.cloud.github.com/assets/6578062/2121152/ef98cf38-91d5-11e3-82aa-2dc834a76df4.png)

**Comment by noxturno** [comment]
didnt seem to be working... there was a dude doing this

**Comment by noxturno** [comment]
now I cant connect... I am the owner... and its giving me that error (your picture)

**Comment by majorcyto** [comment]
It uses IP and UUID for reference in the player profile it stores.. so im not sure how this would be possible realistically.

**Comment by noxturno** [comment]
just happen again. this time tho person banned alot of people and grief spawn

**Comment by Glitch-Goblin** [comment]
if he was able to capture your IP address, possibly by knowing your online location somewhere else, (or it's possible there's a hole in the Starbound client somewhere that lets him see your IP), isn't there  a way to project a false IP addy?
