### ISSUE TITLE
You alive Crashdoom

### ISSUE THREAD

**Issue by majorcyto** [AvilanceLtd/StarryboundServer#76]
You alive Crashdoom? Lol :+1:

**Comment by Crashdoom** [comment]
Yes, there's just a few irl commitments tying me down with regards - Sorry! 

I should be back to normal again soon :P

Anyone who wants to help, feel free to make changed and submit a PR (Pull Request).

**Comment by mauzao9** [comment]
Starbound updated, and there we are incompatible, Uhoh D:

**Comment by majorcyto** [comment]
Yeah x.x...
